# Generated by Django 4.2.7 on 2025-06-06 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutaya', '0003_category_destination'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='destination',
            table='destinations',
        ),
    ]
