# Generated by Django 4.2.7 on 2025-06-06 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutaya', '0004_alter_category_table_alter_destination_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'verbose_name': 'Destination', 'verbose_name_plural': 'Destinations'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='updated_at',
        ),
    ]
