# Generated by Django 4.2.7 on 2025-06-13 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutaya', '0006_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_availabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Travel Availability',
                'verbose_name_plural': 'Travel Availabilities',
                'db_table': 'travel_availabilities',
                'ordering': ['date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
