# Generated by Django 4.2.7 on 2025-06-13 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutaya', '0007_travelavailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('travel_interests', models.JSONField(default=list)),
                ('preferred_environment', models.CharField(blank=True, max_length=50, null=True)),
                ('travel_style', models.CharField(blank=True, max_length=50, null=True)),
                ('budget_range', models.CharField(blank=True, max_length=50, null=True)),
                ('adrenaline_level', models.IntegerField(default=5)),
                ('wants_hidden_places', models.BooleanField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preferences',
                'verbose_name_plural': 'User Preferences',
                'db_table': 'user_preferences',
            },
        ),
    ]
