# Generated by Django 4.2.7 on 2025-06-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutaya', '0009_tourpackage_itineraryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryitem',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
