# Generated by Django 4.2.7 on 2025-06-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutaya', '0010_alter_itineraryitem_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryitem',
            name='datetime',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='start_date',
            field=models.CharField(max_length=255),
        ),
    ]
