# Generated by Django 4.2.7 on 2025-06-25 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutaya', '0011_alter_itineraryitem_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackageRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.CharField(max_length=255)),
                ('tour_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='rutaya.tourpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_package_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tour Package Rate',
                'verbose_name_plural': 'Tour Package Rates',
                'db_table': 'tour_package_rates',
                'ordering': ['-id'],
                'unique_together': {('tour_package', 'user')},
            },
        ),
        migrations.CreateModel(
            name='DestinationRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.CharField(max_length=255)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='rutaya.destination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Destination Rate',
                'verbose_name_plural': 'Destination Rates',
                'db_table': 'destination_rates',
                'ordering': ['-id'],
                'unique_together': {('destination', 'user')},
            },
        ),
    ]
